FROM php:8.3-fpm 

RUN sed -i 's/9000/9085/' /usr/local/etc/php-fpm.d/zz-docker.conf 

WORKDIR /var/www/PDS_APP

RUN apt-get update \
    && apt-get install -y\
    libzip-dev \
    curl \
    zip \
    unzip

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo pdo_mysql\
    && docker-php-ext-install zip

RUN php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN groupadd -g 1000 www 
RUN useradd -u 1000 -ms /bin/bash -g www www

COPY --chown=www:www . /var/www/PDS_APP

USER www

CMD ["php-fpm"]